Add a check in pre-inst-env for existance of the custom guix module

diff --git a/pre-inst-env b/pre-inst-env
--- a/pre-inst-env
+++ b/pre-inst-env
@@ -25,6 +25,11 @@ export GUIX_PACKAGE_PATH="$GDS_GUIX_ROOT/.guix-package-path${GUIX_PACKAGE_PATH:+
 GDS_GNU_GUIX_MODULE_PATH="${GDS_GNU_GUIX_MODULE_PATH%/}"
 
 if [ -n "$GDS_GNU_GUIX_MODULE_PATH" ]; then
+    if [ ! -d "$GDS_GNU_GUIX_MODULE_PATH" ]; then
+        echo "error: pre-inst-env: GDS_GNU_GUIX_MODULE_PATH $GDS_GNU_GUIX_MODULE_PATH does not exist"
+        exit 1
+    fi
+
     export GUILE_LOAD_PATH="$GDS_GNU_GUIX_MODULE_PATH:$GUILE_LOAD_PATH"
     export GUILE_LOAD_COMPILED_PATH="$GDS_GNU_GUIX_MODULE_PATH:$GUILE_LOAD_COMPILED_PATH"
 fi
